services:
  elsa-server-and-studio:
    image: elsaworkflows/elsa-server-and-studio-v3:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      HTTP_PORTS: 8080
      HTTP__BASEURL: http://localhost:14000
    ports:
      - "14000:8080"
  
  elsa-studio:
    image: elsaworkflows/elsa-studio-v3:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      HTTP_PORTS: 8080
      HTTP__BASEURL: http://localhost:13000
      ELSASERVER__URL: http://localhost:12000/elsa/api
    ports:
      - "13000:8080"
  
  elsa-server:
    image: elsaworkflows/elsa-server-v3:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      HTTP_PORTS: 8080
      HTTP__BASEURL: http://localhost:12000
    ports:
      - "12000:8080"