services:
  
  # Elsa Studio and Server from a single image.
  elsa-server-and-studio:
    image: elsaworkflows/elsa-server-and-studio-v3-3-0-preview:latest
    pull_policy: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      HTTP_PORTS: 8080
      HOSTING__BASEURL: http://localhost:14000
      HOSTING__BASEPATH:
    ports:
      - "14000:8080"
    networks:
      - elsa-network

networks:
  elsa-network:
    driver: bridge